swagger: "2.0"
info: {}
basePath: /v1
paths:
  /category/:
    get:
      tags:
      - category
      description: Get category
      operationId: CategoryController.Get category
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      responses:
        "200":
          description: string
        "400":
          description: string
  /food/:
    get:
      tags:
      - food
      description: Get food
      operationId: FoodController.Get food
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      responses:
        "200":
          description: string
        "400":
          description: string
    put:
      tags:
      - food
      description: Put
      operationId: FoodController.Put food
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      - in: body
        name: body
        description: food
        required: true
        schema:
          $ref: '#/definitions/models.Food'
      responses:
        "200":
          description: string
        "400":
          description: string
    post:
      tags:
      - food
      description: Post
      operationId: FoodController.Post food
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      - in: body
        name: body
        description: food
        required: true
        schema:
          $ref: '#/definitions/models.Food'
      responses:
        "200":
          description: string
        "400":
          description: string
  /food/{id}:
    delete:
      tags:
      - food
      description: Put
      operationId: FoodController.Detele food
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      - in: path
        name: id
        description: food id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: string
        "400":
          description: string
  /main/:
    get:
      tags:
      - main
      description: Get
      operationId: MainController.Get
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      responses:
        "200":
          description: string
        "400":
          description: string
  /menu/:
    get:
      tags:
      - menu
      description: Get menu
      operationId: MenuController.Get menu
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      responses:
        "200":
          description: string
        "400":
          description: string
    post:
      tags:
      - menu
      description: Post
      operationId: MenuController.Post menu
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      - in: body
        name: body
        description: menu
        required: true
        schema:
          $ref: '#/definitions/models.Menu'
      responses:
        "200":
          description: string
        "400":
          description: string
  /menu/detail:
    get:
      tags:
      - menu
      description: Get detail menu
      operationId: MenuController.Get detail menu
      parameters:
      - in: header
        name: Auth
        description: token
        required: true
        type: string
      responses:
        "200":
          description: string
        "400":
          description: string
  /store/:
    get:
      tags:
      - store
      description: Get
      operationId: StoreController.Get
      responses:
        "200":
          description: string
        "400":
          description: string
  /store/comment:
    get:
      tags:
      - store
      description: Comment
      operationId: StoreController.Comment
      responses:
        "200":
          description: string
        "400":
          description: string
definitions:
  models.Food:
    title: Food
    type: object
    properties:
      category_id:
        type: integer
        format: int64
      content:
        type: string
      create_date:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      image:
        type: string
      init_price:
        type: string
      menu_id:
        type: integer
        format: int64
      name:
        type: string
      sale_price:
        type: string
      status:
        type: integer
        format: int64
      store_id:
        type: integer
        format: int64
      title:
        type: string
      update_date:
        type: integer
        format: int64
  models.Menu:
    title: Menu
    type: object
    properties:
      create_date:
        type: integer
        format: int64
      id:
        type: integer
        format: int64
      name:
        type: string
      store_id:
        type: integer
        format: int64
      update_date:
        type: integer
        format: int64
